# Generated by Django 2.2.7 on 2021-10-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Standard', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=255)),
                ('age', models.FloatField()),
                ('Place', models.CharField(max_length=255)),
                ('DOB', models.FloatField()),
                ('Student_id', models.FloatField()),
                ('Language', models.CharField(max_length=255)),
                ('Phone_number', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
